language: ruby
dist: trusty
addons:
  sonarcloud:
    organization: "probakilla-github"
    token: "891cd91ec06d87058565b9a6b6fa48dbe0ef29e8"
script:
  - sonar-scanner
  - ruby tests/test_suite_runner.rb